query {
  aggregateAttributes 
 {
    _avg {
      id
      prod_id
    }
    _count {
      _all
      allow_html_tags_storefront
      attribute_class
      attribute_code
      attribute_value
      column_options
      default_label
